title: Optimization Wiki
description: A "Wiki" to help users actually play their games
theme: just-the-docs
color_scheme: dark

url: https://Optimization-Wiki.github.io
baseurl: /

aux_links_new_tab: true
aux_links:
  Our Github: https://github.com/Vxrpenter/Optimization-Wiki

heading_anchors: true

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  attention:
    title: Attention
    color: yellow
  deprecated:
    title: Deprecated
    color: red
  new:
    title: New
    color: green

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"


gh_edit_link: true
gh_edit_link_text: "Contribute to this page."
gh_edit_repository: "https://github.com/Vxrpenter/Optimization-Wiki"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"